### ISSUE TITLE
`julia-last-open-block-pos` broken on latest version on NonGNU ELPA (0.4)

### ISSUE THREAD

**Issue by suhail-singh** [JuliaEditorSupport/julia-emacs#212]
Both `melpa-stable` and `NonGNU` ELPA are at version `0.4`.  However, the two
versions, while nominally being the same, differ in functionality.  The version
on `melpa-stable` corresponds to the git tag which references commit
8bfc709716a257521cb386f20b8932e83db930a9 dated `2020-03-09`.  Whereas the
version on `nongnu` ELPA correspond to
6408b96c1c97e41bc2af060d661afee4f7b22e89 dated `2019-11-13` which is when the
`Version` in the package header first was bumped to `0.4`.  Interestingly, this
commit also introduced a bug in `julia-last-open-block-pos` as a result of an
"over-enthusiastic" renaming.  The result of this bug is that pressing `TAB` to
indent in blocks is broken.

Now, the very next commit (9df3a7ec32f3587dd3a590ae37535fdea6e88a0d) on
`2019-11-13` fixed the bug.  On `2020-03-09` this commit was
released via the `0.4` tag and made its way into `melpa-stable`.  Unfortunately,
since the version in package header wasn't updated, this commit (and subsequent
ones) never made their way into `nongnu` ELPA.

## Proposal

Given the peculiarities of `nongnu` (and `gnu`) ELPA releases, I propose that a
version `0.5` be created, with the earliest commit where the version in the
package header is updated to `0.5`, being the one that is tagged with `0.5`.
Doing so will bring `melpa-stable` and `nongnu` ELPA releases in sync.

Thereafter, (in the very next commit) I propose that the version in package
header be updated to `0.5.50-git` (assuming that you expect the next release to
be either `0.6` or `1.0`) or `0.5.0.50-git` (if you'd like to keep the option
open for the next release to be `0.5.1`).  The `-git` suffix will be ignored by
`nongnu` ELPA.  Once you're ready to release the subsequent version, you can
once again make a commit to bump the version in the package header, and add a
git tag (ensuring that `melpa-stable` and `nongnu` version continue to be
synchronized).

## References

See [this comment](https://github.com/melpa/melpa/issues/2955#issuecomment-1519154736)
and associated discussion in case you'd like to know more about ELPA versioning.

**Comment by tpapp** [comment]
Since we do not make stable releases (effectively, it is just rolling on `master`, I think we should just clarify that users should use `melpa`, and if possible expunge the package from `melpa-stable` etc.

**Comment by meedstrom** [comment]
Bad news if you want to just have a rolling master: emacs 30 is going to make that difficult because of a radical default setting for the new `(use-package :vc)`. So users who install through that method would experience the same issue as described in this thread, even if the package is taken off nongnu and melpa-stable.

https://lists.gnu.org/archive/html/emacs-devel/2024-09/msg00366.html

**Comment by meedstrom** [comment]
You are right - with this distributed on MELPA, it's unlikely anyone would have reason to install through a manual use-package :vc recipe. Sorry for the distraction. 

I am just concerned about packages not on MELPA. Having to ask users to add a :rev :newest would require every user to read the README, and I believe that would be poor design for Emacs, since people don't read READMEs. Anyway, it's up to them now.

>  the project doesn't make stable releases, and
>  thus, users are recommended to only use the latest release.

You might want to add a `:version-regexp regexp-unmatchable` to the MELPA recipe, so it does not get hosted on MELPA Stable. 

I wonder if it is possible for a package to check at runtime which version it is, so it knows if it was installed from NonGNU and can warn the user that it should be installed from NonGNU-devel instead.

**Comment by alphapapa** [comment]
> Bad news if you want to just have a rolling master: emacs 30 is going to make that difficult because of a radical default setting for the new `(use-package :vc)`.

You'll forgive the intrusion, but you did link this issue on emacs-devel, and I would like to be clear about something: this default setting for the new `vc-package` feature is equivalent to how GNU ELPA handles Elisp packages, so I don't think it's fair to accuse it of being "radical."

You seem to be expecting--and nearly demanding--that Emacs mold itself to MELPA's distribution model, which, although it works well in practice, would be more fairly described as "radical", given its use of incompatible, timestamp-based "version" strings.

Really, it makes no sense, in the first place, for a package's version number to not change while the code itself is changing.  One might as well set the version number to `0`, which would communicate as much meaning and be just as useful.  Developers who choose to not meaningfully version their software are responsible for such decisions, and it isn't fair to expect Emacs to work around such practices.

Not only is it trivially easy and quick to actually update version numbers meaningfully, but it's helpful to users and downstream packagers (e.g. Debian, Guix, Nix, Gentoo).  For anything but the most trivial or early-in-development software, it should be done.

**Comment by meedstrom** [comment]
I agree that the version numbers of MELPA are a problem, but it's beside the issue. (I also understand it's on the way to being fixed.)

The core of the model is really that *you fetch the latest commit*.  That is the only safe default if you are fetching from packages not on GNU/NonGNU ELPA, since when they are not on those ELPAs, that means none of them underwent any implicit nor explicit agreement to version their software.

I say "radical" descriptively: anything that diverges from currently established norm and threatens to shatter consensus is radical. That's just the meaning of the word.

It has been community norm that you *could* do what @tpapp wanted, and do only rolling releases. It didn't use to cause anyone any problems. I have trouble agreeing with moves that knowingly break this, and offload the problem to individual users to solve at installation time.

**Comment by meedstrom** [comment]
>  You seem to be expecting--and nearly demanding--that Emacs mold itself to MELPA's distribution model, which, although it works well in practice, would be more fairly described as "radical", given its use of incompatible, timestamp-based "version" strings.

I do not demand that, sorry if it sounds that way.  Versions are good, but if and only if you can expect the developer to version reliably!  

I expect them to think about what kind of user even uses `use-package :vc` and for what.  It's very unpragmatic to behave the same way for packages on ELPA as for packages not on it, unless the goal is to damage the reputations of developers who did not want to version their software yet or who are not very in the loop. Then it's perfect.

**Comment by alphapapa** [comment]
It seems that you don't quite realize that MELPA is its own world; Emacs (and related projects like GNU ELPA) is also its own world.  Emacs very intentionally does not conform to the behavior of MELPA, and MELPA very intentionally diverges from Emacs's own practices.  MELPA is designed to complement Emacs, not vice versa.  That's not going to change, nor should it.  Both projects are useful and successful in their own way.

Eventually GNU ELPA and nonGNU ELPA may obsolete MELPA to some extent.  MELPA's ability to iterate and explore more quickly has helped lead the way for Emacs to follow with more formalized solutions, which is a common pattern in FOSS.  Or MELPA may continue to be widely useful for people who want a less formalized process, which is also fine.

The mistake is in expecting Emacs to conform to someone else's ideas or practices.  That's not how Emacs has ever worked, and with good reason.  Emacs is developed by considering the problem and what the best solutions may be, taking into account what has been done and what exists, but not necessarily doing the same things the same ways.  That's why Emacs is still going strong after 4 decades.

**Comment by tpapp** [comment]
@alphapapa: I appreciate that you took the time to comment here. You convinced me that we should take versioning seriously: it is indeed a minor effort, and serves so many useful purposes (and incidentally, the general registry of the Julia package ecosystem enforces a versioning policy already, which all Julia devs conform to religiously --- I see no point in making an exception for our Emacs environment). 

I will leave this issue open, while I make a PR that also clarifies our new release model.
