### ISSUE TITLE
Plans for a release?

### ISSUE THREAD

**Issue by kyleam** [JuliaEditorSupport/julia-emacs#46]
Hello,

I'd like to add julia-mode to Guix.  A Guix package is typically
defined using the last released version (though an arbitrary commit
can be used if necessary).  Looking through the repo history, the
version was set to 0.3 in 6105b93 (Header improvements to conform to
MELPA's standards., 2014-08-12) and has not been updated since.

Are there any plans to tag a release?

Thanks.

**Comment by phikal** [comment]
I'd also like to raise this question, since without a stable tag, it won't appear in the [MELPA Stable](https://stable.melpa.org/#/) repositories, thus also preventing it from installing any package that depends on `julia-mode` (such as ESS).

**Comment by tpapp** [comment]
I think we should clean up for release on MELPA Stable (it is mostly linting and style conventions, and they may review the code which could be handy). @rfourquet, what do you think?

**Comment by rfourquet** [comment]
I'm not familiar with how MELPA works... and am not sure what cleaning is needed. I'm all for bumping the version number though.

**Comment by tpapp** [comment]
I have released on MELPA before, so I am familiar with the process, will do it.

**Comment by tpapp** [comment]
It would be great to merge the following before a MELPA releast: 

- [ ] #81
- [ ] #83

**Comment by non-Jedi** [comment]
@tpapp for what it's worth, my understanding is that there's no additional review from melpa once a package is merged for subsequent versions. Melpa stable simply grabs the last tagged release of a package.

**Comment by tpapp** [comment]
Yes, but there is an initial review for the first submission. This requires a bit of a cleanup. I plan to do this after #86 is fixed.

**Comment by non-Jedi** [comment]
I'm confused. This package is [already available in melpa](https://github.com/melpa/melpa/blob/master/recipes/julia-mode). Is there a different first submission I'm missing?

**Comment by tpapp** [comment]
No, you are right: I was searching for the package under the name `julia-emacs`, and did not realize it was already in MELPA. In that case, disregard what I said above; there is no reason we cannot release before #86 --- in fact, it would be a good idea so that the potential Emacs23 users would have something they could keep using.

Any suggestions for a version number?

Also, should I just tag a release now, or should we wait for something to get merged?

**Comment by rfourquet** [comment]
> Any suggestions for a version number?

Where can I find the current version number?

Otherwise yes it seems like a good idea to make a release right before droping support for Emacs 23.
I don't have anything in mind which should be merged before it, but I didn't quite follow closely the state of the open PRs recently, sorry (I will try to have a look soon, but feel free to (re)-ping me on specific ones).

**Comment by tpapp** [comment]
The version number is in the code header in the `julia-mode.el` file.

We have now released 0.3, and I plan to make releases regularly as features or fixes accumulate.
