### ISSUE TITLE
Indentation for large code blocks

### ISSUE THREAD

**Issue by yuyichao** [JuliaEditorSupport/julia-emacs#5]
There's currently a limit of lines/statement per code blocks that can be indented correctly. It is a pretty large limit but can be seen when indenting a large function (e.g. some in `inference.jl`).

Reproduce with

```
function f()
    g = begin
        function ()
            return begin
                1
            end
        end
    end
    # repeat the `g =` block above ~150 times.
end
```

Ref https://github.com/JuliaLang/julia/issues/9831 (the original issue of arguments/list is already fixed)

**Comment by StephenVavasis** [comment]
I think this issue should be closed.  Here is the solution (emacs 24.3.1, with Julia-mode loaded) that was posted on discourse:

M-X customize-variable
(prompt from emacs: customize-variable:) julia-max-block-lookback
(new buffer opens, shows previous value 5000 of this variable)
Type 20000 in the blank next to the variable name.
Click "Apply and Save"
(emacs shows in command line that .emacs file has been rewritten)
C-X C-K to kill this buffer.

**Comment by galenlynch** [comment]
I concur that the default should be increased.

**Comment by aramirezreyes** [comment]
Me too.

**Comment by torfjelde** [comment]
> I think it would be reasonable to have a large value (eg 20000) as the default. It does no harm on a modern computer.

Adding my voice to crowd.

Ran into this issue myself in the case of a laaaarge testset (slightly above 20 000 chars), and just tried increasing `julia-max-block-loop` to more than this, and the slowdown was not even noticable on a not-the-most-modern CPU. So I agree; increasing default is good idea:)

Personally, I also thinks it's better to have issues like "This is super-slow, why is it slow?" rather than "This completely breaks!"
