### ISSUE TITLE
Improve parsing of quoted symbols

### ISSUE THREAD

**Issue by twerq** [JuliaEditorSupport/julia-emacs#55]
For example I take file [julia base client.jl](https://github.com/JuliaLang/julia/blob/master/base/client.jl). Please have a look at line 185:
```
    occursin("\"`\"", msg) && return :cmd
```
In case of GRAVE ACCENT symbol quoted with escaped quotes further highlighting getting failed.

Here is screenshot for convenience
![screenshot from 2018-08-14 17-48-50](https://user-images.githubusercontent.com/166907/44099059-70de6b80-9fea-11e8-92c9-9bec255efa3f.png)

**Comment by yuyichao** [comment]
Basically dup of https://github.com/JuliaEditorSupport/julia-emacs/issues/15. I assume https://github.com/JuliaEditorSupport/julia-emacs/pull/54 fixes this one.

**Comment by twerq** [comment]
Thank you @yuyichao. Maybe you know why #54 not in master so far?

**Comment by yuyichao** [comment]
https://github.com/JuliaEditorSupport/julia-emacs/pull/54#issuecomment-385263143

**Comment by Antigonus** [comment]
Hello,  I've been an emacs user for decades.  So of course the first thing I looked for was a julia repl mode.  c-c c-c nicely sent things to the repl.   However, at the command line previous command was not m-p but was c-p - the same control sequence for moving up into the buffer.  I also found that I can not cut and paste on the command line, but am forced to type things by hand.

Hence a person can not, for example, chop something out of the transcript somewhere, move up in the buffer, and past it in so as to make a comparison.  One can not chop an argument out of one buffer and then paste it into a command being typed, or job part of a typed command and then go drop it in another buffer. This was frustrating, and a bit of time waster.

It would seem to me that the point of running a repl in Emacs is so that emacs functions can apply uniformly.   That the programmer is not 'controlled' by the interface, but the other way around ...

Anyway just an initial impression.  Take it for what it is worth. I'm sure you all have your design goals.  .. It was interesting to see so much in common between Julia and Common Lisp.  Good luck with it.

Thomas Walker Lynch
thomas@thomas-walker-lynch.com

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by yuyichao** [comment]
@twerq I only point out to him where to add those just now so I'll wait a few days for that. If not and if I remember (or someone reminds me), I'll merge in a few days.

It's not as critical as base julia test but having one is still better and merging without one will make it much less likely to have one later until it actually regress again.

**Comment by yuyichao** [comment]
@Antigonus I'm not sure what you want to say. If you have an issue about the repl mode, feel free to open an issue or comment on one of the relavant issues instead of an unrelated one. In any case, this doesn't seem to be related to this issue at all so I'll delete the copy here (again, feel free to post in a new issue or discourse post, whichever you prefer).

FWIW, I never find any emacs repl/term mode useful so I have no comment on that, other people might if you post to the right place.
